### ISSUE TITLE
Some issues in the code

### ISSUE THREAD

**Issue by nithissh1** [vavkamil/h1_2_nuclei#1]
Traceback (most recent call last):
  File "/root/tools/h1_2_nuclei/h1_2_nuclei.py", line 200, in <module>
    main(args)
  File "/root/tools/h1_2_nuclei/h1_2_nuclei.py", line 149, in main
    json_scope = check_scope(handle)
  File "/root/tools/h1_2_nuclei/h1_2_nuclei.py", line 49, in check_scope
    json_scope = json_obj["relationships"]["structured_scopes"]["data"]
KeyError: 'relationships'

**Comment by vavkamil** [comment]
Hi, thank you for the heads up. Based on the error message, it's probably a program that doesn't have a defined scope. I will check it out and add an exception to handle this use case. An example of the program handle would be really helpful.
